// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: proto/taskservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskServiceGRPC_CreateTask_FullMethodName        = "/TaskServiceGRPC/CreateTask"
	TaskServiceGRPC_AssignToTask_FullMethodName      = "/TaskServiceGRPC/AssignToTask"
	TaskServiceGRPC_GetTask_FullMethodName           = "/TaskServiceGRPC/GetTask"
	TaskServiceGRPC_GetAllAssigned_FullMethodName    = "/TaskServiceGRPC/GetAllAssigned"
	TaskServiceGRPC_GetAllCreated_FullMethodName     = "/TaskServiceGRPC/GetAllCreated"
	TaskServiceGRPC_UpdateTitle_FullMethodName       = "/TaskServiceGRPC/UpdateTitle"
	TaskServiceGRPC_UpdateDescription_FullMethodName = "/TaskServiceGRPC/UpdateDescription"
	TaskServiceGRPC_UpdateStatus_FullMethodName      = "/TaskServiceGRPC/UpdateStatus"
	TaskServiceGRPC_UpdateDeadline_FullMethodName    = "/TaskServiceGRPC/UpdateDeadline"
	TaskServiceGRPC_UpdatePriority_FullMethodName    = "/TaskServiceGRPC/UpdatePriority"
	TaskServiceGRPC_DeleteTask_FullMethodName        = "/TaskServiceGRPC/DeleteTask"
	TaskServiceGRPC_UnassignTask_FullMethodName      = "/TaskServiceGRPC/UnassignTask"
)

// TaskServiceGRPCClient is the client API for TaskServiceGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceGRPCClient interface {
	// Create
	CreateTask(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	AssignToTask(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Read
	GetTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAllAssigned(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetAllCreated(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	// Update
	UpdateTitle(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateDescription(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateDeadline(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdatePriority(ctx context.Context, in *UpdatePriorityRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Delete
	DeleteTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UnassignTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type taskServiceGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceGRPCClient(cc grpc.ClientConnInterface) TaskServiceGRPCClient {
	return &taskServiceGRPCClient{cc}
}

func (c *taskServiceGRPCClient) CreateTask(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) AssignToTask(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_AssignToTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) GetTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) GetAllAssigned(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_GetAllAssigned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) GetAllCreated(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_GetAllCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UpdateTitle(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UpdateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UpdateDescription(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UpdateDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UpdateDeadline(ctx context.Context, in *UpdateStringRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UpdateDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UpdatePriority(ctx context.Context, in *UpdatePriorityRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UpdatePriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) DeleteTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceGRPCClient) UnassignTask(ctx context.Context, in *IDOnlyRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, TaskServiceGRPC_UnassignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceGRPCServer is the server API for TaskServiceGRPC service.
// All implementations must embed UnimplementedTaskServiceGRPCServer
// for forward compatibility.
type TaskServiceGRPCServer interface {
	// Create
	CreateTask(context.Context, *CreateRequest) (*SuccessResponse, error)
	AssignToTask(context.Context, *AssignRequest) (*SuccessResponse, error)
	// Read
	GetTask(context.Context, *IDOnlyRequest) (*GetResponse, error)
	GetAllAssigned(context.Context, *IDOnlyRequest) (*GetAllResponse, error)
	GetAllCreated(context.Context, *IDOnlyRequest) (*GetAllResponse, error)
	// Update
	UpdateTitle(context.Context, *UpdateStringRequest) (*SuccessResponse, error)
	UpdateDescription(context.Context, *UpdateStringRequest) (*SuccessResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*SuccessResponse, error)
	UpdateDeadline(context.Context, *UpdateStringRequest) (*SuccessResponse, error)
	UpdatePriority(context.Context, *UpdatePriorityRequest) (*SuccessResponse, error)
	// Delete
	DeleteTask(context.Context, *IDOnlyRequest) (*SuccessResponse, error)
	UnassignTask(context.Context, *IDOnlyRequest) (*SuccessResponse, error)
	mustEmbedUnimplementedTaskServiceGRPCServer()
}

// UnimplementedTaskServiceGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceGRPCServer struct{}

func (UnimplementedTaskServiceGRPCServer) CreateTask(context.Context, *CreateRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServiceGRPCServer) AssignToTask(context.Context, *AssignRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignToTask not implemented")
}
func (UnimplementedTaskServiceGRPCServer) GetTask(context.Context, *IDOnlyRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceGRPCServer) GetAllAssigned(context.Context, *IDOnlyRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAssigned not implemented")
}
func (UnimplementedTaskServiceGRPCServer) GetAllCreated(context.Context, *IDOnlyRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCreated not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UpdateTitle(context.Context, *UpdateStringRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTitle not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UpdateDescription(context.Context, *UpdateStringRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDescription not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UpdateDeadline(context.Context, *UpdateStringRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeadline not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UpdatePriority(context.Context, *UpdatePriorityRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePriority not implemented")
}
func (UnimplementedTaskServiceGRPCServer) DeleteTask(context.Context, *IDOnlyRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskServiceGRPCServer) UnassignTask(context.Context, *IDOnlyRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignTask not implemented")
}
func (UnimplementedTaskServiceGRPCServer) mustEmbedUnimplementedTaskServiceGRPCServer() {}
func (UnimplementedTaskServiceGRPCServer) testEmbeddedByValue()                         {}

// UnsafeTaskServiceGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceGRPCServer will
// result in compilation errors.
type UnsafeTaskServiceGRPCServer interface {
	mustEmbedUnimplementedTaskServiceGRPCServer()
}

func RegisterTaskServiceGRPCServer(s grpc.ServiceRegistrar, srv TaskServiceGRPCServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskServiceGRPC_ServiceDesc, srv)
}

func _TaskServiceGRPC_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).CreateTask(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_AssignToTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).AssignToTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_AssignToTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).AssignToTask(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).GetTask(ctx, req.(*IDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_GetAllAssigned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).GetAllAssigned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_GetAllAssigned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).GetAllAssigned(ctx, req.(*IDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_GetAllCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).GetAllCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_GetAllCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).GetAllCreated(ctx, req.(*IDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UpdateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UpdateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UpdateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UpdateTitle(ctx, req.(*UpdateStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UpdateDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UpdateDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UpdateDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UpdateDescription(ctx, req.(*UpdateStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UpdateDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UpdateDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UpdateDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UpdateDeadline(ctx, req.(*UpdateStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UpdatePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UpdatePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UpdatePriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UpdatePriority(ctx, req.(*UpdatePriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).DeleteTask(ctx, req.(*IDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskServiceGRPC_UnassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceGRPCServer).UnassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskServiceGRPC_UnassignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceGRPCServer).UnassignTask(ctx, req.(*IDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskServiceGRPC_ServiceDesc is the grpc.ServiceDesc for TaskServiceGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskServiceGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskServiceGRPC",
	HandlerType: (*TaskServiceGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskServiceGRPC_CreateTask_Handler,
		},
		{
			MethodName: "AssignToTask",
			Handler:    _TaskServiceGRPC_AssignToTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskServiceGRPC_GetTask_Handler,
		},
		{
			MethodName: "GetAllAssigned",
			Handler:    _TaskServiceGRPC_GetAllAssigned_Handler,
		},
		{
			MethodName: "GetAllCreated",
			Handler:    _TaskServiceGRPC_GetAllCreated_Handler,
		},
		{
			MethodName: "UpdateTitle",
			Handler:    _TaskServiceGRPC_UpdateTitle_Handler,
		},
		{
			MethodName: "UpdateDescription",
			Handler:    _TaskServiceGRPC_UpdateDescription_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _TaskServiceGRPC_UpdateStatus_Handler,
		},
		{
			MethodName: "UpdateDeadline",
			Handler:    _TaskServiceGRPC_UpdateDeadline_Handler,
		},
		{
			MethodName: "UpdatePriority",
			Handler:    _TaskServiceGRPC_UpdatePriority_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskServiceGRPC_DeleteTask_Handler,
		},
		{
			MethodName: "UnassignTask",
			Handler:    _TaskServiceGRPC_UnassignTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/taskservice.proto",
}
